/**
 * Supplier invoice — the accounts payable (CxP) document.
 *
 * Three-way match: purchase order (price) ↔ goods receipt (quantity) ↔
 * invoice. Quantities can never exceed what was received and not yet
 * invoiced (hard rule). Price variances above the tolerance put the invoice
 * ON_HOLD until someone with finance.approve releases it.
 *
 * Accounting entries (AP journal) are generated by the finance phase from
 * POSTED invoices; this module keeps the payable subledger.
 */
import type { TxSession } from '../../tenant/domain/ports';

export type SupplierInvoiceStatus = 'ON_HOLD' | 'POSTED' | 'PARTIALLY_PAID' | 'PAID' | 'CANCELLED';

export interface SupplierInvoiceLine {
  productId: string;
  quantity: number;
  unitCost: number;
  /** Purchase order unit cost at match time. */
  orderUnitCost: number;
}

export interface MatchIssue {
  productId: string;
  type: 'PRICE_VARIANCE';
  orderUnitCost: number;
  invoiceUnitCost: number;
  variancePct: number;
}

export interface SupplierInvoice {
  _id: string;
  tenantId: string;
  folio: string;
  supplierInvoiceNumber: string;
  supplierId: string;
  purchaseOrderId: string;
  purchaseOrderFolio: string;
  currency: string;
  invoiceDate: string;
  dueDate: string;
  lines: SupplierInvoiceLine[];
  subtotal: number;
  taxRate: number;
  taxAmount: number;
  total: number;
  amountPaid: number;
  balance: number;
  status: SupplierInvoiceStatus;
  matchIssues: MatchIssue[];
  releasedBy?: string;
  releasedAt?: Date;
  notes?: string;
  createdBy: string;
  createdAt: Date;
  updatedAt: Date;
  version: number;
}

export interface SupplierInvoiceFilters {
  supplierId?: string;
  purchaseOrderId?: string;
  status?: SupplierInvoiceStatus;
  /** Only invoices with a pending balance (POSTED / PARTIALLY_PAID). */
  open?: boolean;
}

export interface ISupplierInvoiceStore {
  create(data: Omit<SupplierInvoice, '_id' | 'createdAt' | 'updatedAt' | 'version'>, session: TxSession): Promise<SupplierInvoice>;
  findById(tenantId: string, id: string, session?: TxSession): Promise<SupplierInvoice | null>;
  findBySupplierNumber(tenantId: string, supplierId: string, number: string, session?: TxSession): Promise<SupplierInvoice | null>;
  list(tenantId: string, filters: SupplierInvoiceFilters, page: number, limit: number): Promise<{
    data: SupplierInvoice[];
    total: number;
    page: number;
    limit: number;
    totalPages: number;
  }>;
  /** Every open invoice (for aging); bounded by the caller. */
  listOpen(tenantId: string, supplierId?: string): Promise<SupplierInvoice[]>;
  setStatus(tenantId: string, id: string, patch: { status: SupplierInvoiceStatus; releasedBy?: string; releasedAt?: Date }, expectedVersion: number, updatedBy: string, session?: TxSession): Promise<SupplierInvoice | null>;
}

export const INVOICE_FOLIO_PREFIX = 'FAP';
/** Price variance tolerated without a hold (fraction, 0.005 = 0.5%). */
export const PRICE_TOLERANCE = 0.005;

export const AGING_BUCKETS = ['current', 'd1_30', 'd31_60', 'd61_90', 'd90_plus'] as const;
export type AgingBucket = (typeof AGING_BUCKETS)[number];

/** Days past due → aging bucket (not yet due = current). */
export function agingBucket(dueDate: string, today: Date): AgingBucket {
  const due = new Date(`${dueDate}T00:00:00Z`).getTime();
  const now = Date.UTC(today.getUTCFullYear(), today.getUTCMonth(), today.getUTCDate());
  const days = Math.floor((now - due) / 86_400_000);
  if (days <= 0) return 'current';
  if (days <= 30) return 'd1_30';
  if (days <= 60) return 'd31_60';
  if (days <= 90) return 'd61_90';
  return 'd90_plus';
}

export function addDays(isoDate: string, days: number): string {
  const d = new Date(`${isoDate}T00:00:00Z`);
  d.setUTCDate(d.getUTCDate() + days);
  return d.toISOString().slice(0, 10);
}
